config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homes/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  get 'home/about', to: 'homes#about', as: 'home'
  resources :users 
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, length: {maximum: 20},  presence: true
  validates :name, length: {minimum: 2}
  validates :introduction, length: {maximum: 50}
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,:configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def authenticate
    unless user_signed_in?
      redirect_to new_user_session_path, :notice => 'if you want to add a notice'
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    if @user != @current_user
      redirect_to user_path(current_user)
    end
  end

  def correct_book
    @book = Book.find(params[:id])    
    @user = @book.user
    if @user != @current_user
      redirect_to books_path
    end
  end

end


  
  # def authenticate
  #   return if logged_in?
  #   return_to new_user_session_path
  #   end
    
  #   def logged_in?
  #   !!session[:user_id]
  #   end

  # def correct_book
  #   @post = current_user.posts.find_by(id: params[:id])
  #   unless @post
  #     redirect_to books_path
  #   end
  # end

    # def correct_user
  #   @post = current_user.posts.find_by(id: params[:id])
  #   unless @post
  #     redirect_to user_path(current_user)
  #   end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate
  before_action :correct_book, only: [:edit, :update]

  def index
    @user = User.find(current_user.id)
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render action: :index
    end
  end

  def new
    @books = Book.alls
    @book = Book.new(book_params)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find_by(id:params[:id])
    @books = @book.user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: 'Book was successfully created.'
    else
      @books = Book.all
      @user = User.find_by(id:params[:id])
      render action: :index
    end
  end

  def destroy  
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
  end

  private
    def book_params
        params.require(:book).permit(:title, :body)
    end

end


  # def correct_book
  #   @post = current_user.posts.find_by(id: params[:id])
  #   unless @post
  #     redirect_to books_path
  #   end
  # end

# if  @user != @current_user
        #   redirect_to book_path(current_user.id) and return
        #   @boook = save
        # end

 # if @user != @current_user
        #   redirect_to book_path(current_user.id) and return
        # end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate
  before_action :correct_user, only: [:edit, :update]

  def home
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def create
    @user.id = current_user.id
    @user = user.new(user_params)
    if @user.save
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def new
    @user = User.new(user_params)
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if 
      @user.update(user_params)
      redirect_to user_path(@user), notice: 'Book was successfully updated.'
    else
      render action: :edit
    end
  end

  def destroy
  end

  private
    def user_params
        params.require(:user).permit(:name, :introduction, :profile_image)
    end
    
end

# @user = User.find(params[:id])

# if @user != @current_user
        #     redirect_to user_path(current_user.id) and return
        # end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<div class="container">

  <div class="container">
    <h1>Editing Book</h1>
  </div>
  
  <%= render 'users/form', book: @book %>

  <%= link_to 'Show', book_path %> |
  <%= link_to 'Back', books_path %>

</div>

app/views/books/index.html.erb
<div class="container-fluid">
  <div class="row">
      
    <div class="col-2 offset-md-2">
      <div class="container pt-3"><h1>User info</h1></div> 

        <table class="table">
          <tr><th><%= attachment_image_tag @user, :profile_image, :fill, 70, 70, format: 'jpg', fallback: "no_image.jpg" %></th></tr>
          <tr><th><div class="container">
          <p>name</p>
          <%= @user.name %>
          </div></th></tr>
          <tr><th><div class="container">
          <p>introduction</p>
          <%= @user.introduction %>
          </div></th></tr>
          <tr><th><button type="button" class="btn btn-outline-primary"><%= link_to 'EDIT', edit_user_path(current_user) %></button></th></tr>
        </table>
        
      <div class="container"><h2>New book</h2></div>

      <%= render 'users/form', book:@book %>

    </div

    <div class="col-6">
    <div class="container pt-4"><h2>Books<h2></div>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

      <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
              <div class="container"><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 75, 75, format: 'jpg', fallback: "no_image.jpg"), user_path(book.user) %>
              </div></td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
    <div class="offset-md-2"></div>

</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-2 offset-md-2">
      <div class="container pt-3"><h1>User info</h1></div> 
      <p id="notice"><%= notice %></p>                 
        <table class="table">
          <tr><th><%= attachment_image_tag @book.user, :profile_image, :fill, 70, 70, format: 'jpg', fallback: "no_image.jpg" %></th></tr>
          <tr><th><div class="container">
            <p>name</p>
            <%= @book.user.name %></div></th></tr>
          <tr><th><div class="container">
            <p>introduction</p>
            <%= @book.user.introduction %></div></th></tr>
          <tr><th><button type="button" class="btn btn-outline-primary"><%= link_to 'EDIT', edit_user_path(current_user) %></button></th></tr>
        </table>
      <div class="container"><h2>New book</h2></div>
      
      
      <%= form_for(@book) do |form| %>
        <% if @book.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved: successfully</h2>
            <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      
        <p id="notice"><%= notice %></p>
      
        
        <table class="table">
          <tr>
          <div class="field">
          <th><%= form.label :Title %></th>
          <th><%= form.text_field :title %></th>
          </div>
          </tr>
          <tr>
        <div class="field">
          <th><%= form.label :Opinion %></th>
          <th><%= form.text_area :body %></th>
        </div>
          </tr>
          <tr>
          <div class="actions">
        <% if @user == @current_user %>
          <div class="actions">
          <th><%= form.submit "Create Book" %></th>
          </div>
          <% else %>
          <tr><th><button type="button" class="btn btn-outline-primary"><%= link_to 'Create Book', books_path(@book) %></button></th></tr>
        <% end %>
        </tr>
        </table>
      <% end %>



    </div>
    <div class="col-6">
      <div class="container pt-4"><h2>Book detail<h2></div>
      <%= form_for(@book) do |form| %>
        <% if @book.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
            <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
      <% end %>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><div class="container">
            <%= link_to attachment_image_tag(@book.user, :profile_image, :fill, 75, 75, format: 'jpg', fallback: "no_image.jpg"), user_path(@book) %>
          </div><%= link_to @book.user.name, user_path(@books) %></td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
          <% if @book.user == current_user %>
            <td>
              <%= link_to 'Edit', edit_book_path(@book) %>
              <%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          <% end %>
          <% end %>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="offset-md-2"></div>

  </div>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/homes/about.html.erb

<div class="container">
  <div class="container pt-3">
    <h1>welcome to Bookers !!</h1>
  </div>
</div>

app/views/homes/index.html.erb
<div class="container">

  <div class="container pt-3">
    <h1>welcome to Bookers !!</h1>
  </div>
  <div class="container">
    <p>
    In Bookers,<br>
    you can share and exchange your opinions , inpressions , and emotions<br>
    about various books!</p>
  </div>
  
  <div class="container">
    <div class="col p-1">
      
      <button type="button" class="btn btn-outline-primary"><i class="fas fa-archway"></i><%= link_to "sign up", new_user_registration_path, class: 'post' %></button>
    </div>
  </div>
  
  <div class="container">
    <div class="col p-1">
      <button type="button" class="btn btn-outline-primary"><i class="fas fa-archway"></i><%= link_to "log in", new_user_session_path, class: 'post' %></button>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f81ed11e59.js" crossorigin="anonymous"></script>
  </head>
  <body>
  <div classa="container">
    <% if user_signed_in? %> 
    <!-- ユーザーがログインしていた時の処理 -->
      <ul class="nav navbar-dark bg-dark justify-content-end">
      <div class="container-fluid">
        <div class="row">
        <div class="col-2 offset-md-2"><li class="nav-item p-1"><h2 class="h2">Bookers<h2></li></div>

        <div class="offset-md-2"></div>

            <div class="col-1">
            <li class="nav-item p-2">
              <button type="button" class="btn btn-outline-primary"><i class="fas fa-archway"></i><%= link_to "Home", user_path(current_user.id) %></button></li>
              </div>
              <div class="col-1">
            <li class="nav-item p-2">
              <button type="button" class="btn btn-outline-primary"><i class="fas fa-align-left"></i><%= link_to "Users", users_path %></button></li>
              </div>
              <div class="col-1">
            <li class="nav-item p-2">
              <button type="button" class="btn btn-outline-primary"><i class="fab fa-buffer"></i><%= link_to "Books", books_path %></li>
              </div>
              <div class="col-1">
            <li class="nav-item p-2 mr-4">
              <button type="button" class="btn btn-outline-primary"><i class="fas fa-caret-square-down"></i><%= link_to "logout", destroy_user_session_path, method: :delete %></button></li>
              </div>
              <div class="offset-md-2"></div>
              
        </div>
      </div>
      </ul>
    <div>
    <p id="notice"><%= notice %></p>
  <% else %>
  
    <!-- ユーザーがログインしていなかった時の処理 -->
    <div classa="container">
      <ul class="nav navbar-dark bg-dark justify-content-end">
      <div class="container-fluid">
        <div class="row">
          <div class="col-2 offset-md-2"><li class="nav-item p-1"><h2 class="h2">Bookers<h2></li></div>

          <div class="offset-md-2"></div>

          <div class="col-1">
            <li class="nav-item p-2"> 
              <button type="button" class="btn btn-outline-primary"><i class="fas fa-archway"></i><%= link_to "Home", root_path %></button></li>
              </div>
              <div class="col-1">
            <li class="nav-item p-2">
              <button type="button" class="btn btn-outline-primary"><i class="fas fa-align-left"></i><%= link_to "About", home_path %></button></li>
              </div>
              <div class="col-1">
            <li class="nav-item p-2">
              <button type="button" class="btn btn-outline-primary"><i class="far fa-address-card"></i><%= link_to "sign up", new_user_registration_path %></button></li>
              </div>
              <div class="col-1">
            <li class="nav-item p-2 mr-4">
              <button type="button" class="btn btn-outline-primary"><i class="far fa-check-square"></i><%= link_to "login", new_user_session_path %></button></li>
              </div>

              <div class="offset-md-2"></div>
             
        </div>
      </div>
      </ul>
    <div> 
    <p id="notice"><%= notice %></p>
  <% end %>
      <%= yield %>
      
    <div class="container">
      <p>CopyRight Infratop.inc<p>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved: not successfully</h2>
      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p id="notice"><%= notice %></p>

  
  <table class="table">
  <tr>
  <div class="field">
  <th><%= form.label :Title %></th>
  <th><%= form.text_field :title %></th>
  </div>
  </tr>
  <tr>
  <div class="field">
    <th><%= form.label :Opinion %></th>
    <th><%= form.text_area :body %></th>
  </div>
  </tr>
  <tr>
  <div class="actions">
    <th><%= form.submit "Create Book" %></th>
  </div>
  </tr>
  </table>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
  
  <diV class="container pt-3"><h1>User info</h1><div>

  <%= form_for(@user) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
  <p id="notice"><%= notice %></p>

<div class="container">
<%= form_for(@user) do |form| %> 
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>    
  </div>

  <div>Image</div>

  <div>
    <%= form.attachment_field :profile_image %>
  </div>

  <div>
    <%= form.label :introduction %>
    <%= form.text_area :introduction %>
  </div>

  <div>
    <%= form.submit "Update" %>
  </div>
<% end %>
</div

app/views/users/index.html.erb
<div class="container-fluid">
  <div class="row">

  <div class="col-2 offset-md-2">
    <div class="container pt-3"><h1>User info</h1></div> 
    
    <table class="table">
    <tr><th><%= attachment_image_tag @user, :profile_image, :fill, 70, 70, format: 'jpg', fallback: "no_image.jpg" %></th></tr>
    <tr><th><div class="container">
    <p>name</p>
    <%= @user.name %>
    </div></th></tr>
    <tr><th><div class="container">
    <p>introduction</p>
    <%= @user.introduction %>
    </div></th></tr>
    <tr><th><button type="button" class="btn btn-outline-primary"><%= link_to 'EDIT', edit_user_path(current_user) %></button></th></tr>
  </table>


    <div class="container"><h2>New book</h2></div>
    <%= render 'users/form', book:@book %>
  </div>

  <div class="col-6">
  <div class="container pt-4"><h2>User<h2></div>
    <table class="table">
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th colspan="1"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><div class="container">
            <%= attachment_image_tag user, :profile_image, :fill, 75, 75, format: 'jpg', fallback: "no_image.jpg" %>
          </div></td>
            <td><%= user.name %></td>
            <td><%= link_to 'show', user_path(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="offset-md-2"></div>

</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
      
    <div class="col-2 offset-md-2">
      <div class="container pt-3"><h1>User info</h1></div> 
      
      <table class="table">
        <tr><th><%= attachment_image_tag @user, :profile_image, :fill, 70, 70, format: 'jpg', fallback: "no_image.jpg" %></th></tr>
        <tr><th><div class="container">
        <p>name</p>
        <%= @user.name %>
        </div></th></tr>
        <tr><th><div class="container">
        <p>introduction</p>
        <%= @user.introduction %>
        </div></th></tr>
        <tr><th><button type="button" class="btn btn-outline-primary">
        
        <% if @user.id == current_user.id %>
          <%= link_to 'EDIT', edit_user_path(@user) %>
          <% else %>
          <%= link_to 'EDIT', user_path(current_user.id) %>>
        <% end %>
        
        
        
        </button></th></tr>
      </table>


      <div class="container"><h2>New book</h2></div>
      <%= render 'users/form', book:@book %>
    </div>

    <div class="col-6">
      <div class="container pt-4"><h2>Books<h2></div>
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.books.each do |book| %>
            <tr>
              <td><div class="container">
              <%= link_to attachment_image_tag( @user, :profile_image, :fill, 75, 75, format: 'jpg', fallback: "no_image.jpg"), user_path(@user) %>
            </div></td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="offset-md-2"></div>

  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>